<div class="profile-reg-error-div" id="profile-reg-error-div" hidden>
    <?php if (@$_REQUEST["res"] == "ic") { ?>
        <span class="glyphicon glyphicon-remove" ></span> Вы ввели неверную капчу. Попробуйте ещё раз.
    <?php } if (@$_REQUEST["res"] == "nc"){ ?>
        <span class="glyphicon glyphicon-remove" ></span> Вы не ввели капчу.
    <?php }  if (@$_REQUEST["res"] == "nr"){ ?>
        <span class="glyphicon glyphicon-remove" ></span> Не получилось зарегистрировать нового пользователя. Обратитесь к Администратору.
    <?php } ?>
</div>