<div class="profile-reg-message-div">
    <?php if (\Users\Services\FlashSession::hasInfos()) { ?>
    <div class="profile-reg-success-div">
        <ol>
        <?php foreach (\Users\Services\FlashSession::getInfos() as $m) { ?>
            <li><?= $m ?></li>
        <?php } ?>
        </ol>
    <?php } elseif (\Users\Services\FlashSession::hasErrors()) { ?>
    <div class="profile-reg-success-div">
        <ol>
            <?php foreach (\Users\Services\FlashSession::getErrors() as $m) { ?>
                <li><?= $m ?></li>
            <?php } ?>
        </ol>
    <?php } ?>
    <hr>
    <p style="color: lightblue; text-decoration: underline;" onclick="$(this).parent('div').hide();">Закрыть сообщение</p>
</div>
